fastlane_version "2.27.0"
default_platform :ios

platform :ios do
  before_all do
    ENV["FASTLANE_EXPLICIT_OPEN_SIMULATOR"] = "2"
    clear_derived_data
  end

  lane :unit_test do
    spm(
      command: "test",
      build_path: "./build",
      configuration: "debug"
    )
  end

  lane :build_swiftpm do
    spm(
      command: "build",
      build_path: "./build",
      configuration: "release"
    )
  end
end
